### ISSUE TITLE
Некоррректный порт в ссылках на видеолпоток

### ISSUE THREAD

**Issue by kolayuk** [alexmorbo/domru#15]
Изначально проблема в том, что аддон по умолчанию работает на порту 10080, который при использовании Chrome считается [небезопасным](https://superuser.com/questions/188058/which-ports-are-considered-unsafe-by-chrome).
Если же поменять в настройках супервизора порт который будет прокидываться в контейнер - все ссылки все еще ведут на 10080

Решение:
поменять порт по умолчанию или
динамически из конфигурации вытягивать порт который проксируется в контейнер

**Comment by alexmorbo** [comment]
Привет!

Поправлю
