### ISSUE TITLE
Не добавляется интеграция HA 2021.12.10

### ISSUE THREAD

**Issue by eugene-ki** [alexmorbo/domru#17]
Перестала работать интеграция. Ввожу номер телефона, выбираю договор из списка, далее длительное ожидание и ошибка 500. Через приложение Дом.Ру все работает.

Лог аддона:
`16:17:42 DEBUG     [app] HTTP request run ["parameters" => ["_controller" => "App\Command\RunCommand","_method" => "fetchFullInfo","_route" => "fetchFullInfo"],"args" => []]
16:17:42 WARNING   [php] Warning: Invalid argument supplied for foreach() ["exception" => ErrorException { …}]
16:17:44 DEBUG     [app] HTTP request run ["parameters" => ["_controller" => "App\Command\RunCommand","_method" => "fetchFullInfo","_route" => "fetchFullInfo"],"args" => []]
16:17:44 WARNING   [php] Warning: Invalid argument supplied for foreach() ["exception" => ErrorException { …}]
16:17:46 DEBUG     [app] HTTP request run ["parameters" => ["_controller" => "App\Command\RunCommand","_method" => "fetchFullInfo","_route" => "fetchFullInfo"],"args" => []]
16:17:46 WARNING   [php] Warning: Invalid argument supplied for foreach() ["exception" => ErrorException { …}]
16:17:48 DEBUG     [app] HTTP request run ["parameters" => ["_controller" => "App\Command\RunCommand","_method" => "fetchFullInfo","_route" => "fetchFullInfo"],"args" => []]
16:17:48 WARNING   [php] Warning: Invalid argument supplied for foreach() ["exception" => ErrorException { …}]
16:17:50 DEBUG     [app] HTTP request run ["parameters" => ["_controller" => "App\Command\RunCommand","_method" => "fetchFullInfo","_route" => "fetchFullInfo"],"args" => []]
16:17:50 WARNING   [php] Warning: Invalid argument supplied for foreach() ["exception" => ErrorException { …}]
16:17:52 DEBUG     [app] HTTP request run ["parameters" => ["_controller" => "App\Command\RunCommand","_method" => "fetchFullInfo","_route" => "fetchFullInfo"],"args" => []]
16:17:52 WARNING   [php] Warning: Invalid argument supplied for foreach() ["exception" => ErrorException { …}]
16:17:54 DEBUG     [app] HTTP request run ["parameters" => ["_controller" => "App\Command\RunCommand","_method" => "fetchFullInfo","_route" => "fetchFullInfo"],"args" => []]
16:17:54 WARNING   [php] Warning: Invalid argument supplied for foreach() ["exception" => ErrorException { …}]
16:17:56 DEBUG     [app] HTTP request run ["parameters" => ["_controller" => "App\Command\RunCommand","_method" => "fetchFullInfo","_route" => "fetchFullInfo"],"args" => []]
16:17:56 WARNING   [php] Warning: Invalid argument supplied for foreach() ["exception" => ErrorException { …}]
16:17:58 DEBUG     [app] HTTP request run ["parameters" => ["_controller" => "App\Command\RunCommand","_method" => "fetchFullInfo","_route" => "fetchFullInfo"],"args" => []]
16:17:58 WARNING   [php] Warning: Invalid argument supplied for foreach() ["exception" => ErrorException { …}]
16:18:00 DEBUG     [app] HTTP request run ["parameters" => ["_controller" => "App\Command\RunCommand","_method" => "fetchFullInfo","_route" => "fetchFullInfo"],"args" => []]
16:18:00 WARNING   [php] Warning: Invalid argument supplied for foreach() ["exception" => ErrorException { …}]
16:18:02 DEBUG     [app] HTTP request run ["parameters" => ["_controller" => "App\Command\RunCommand","_method" => "fetchFullInfo","_route" => "fetchFullInfo"],"args" => []]
16:18:02 WARNING   [php] Warning: Invalid argument supplied for foreach() ["exception" => ErrorException { …}]
16:18:04 DEBUG     [app] HTTP request run ["parameters" => ["_controller" => "App\Command\RunCommand","_method" => "fetchFullInfo","_route" => "fetchFullInfo"],"args" => []]
16:18:04 WARNING   [php] Warning: Invalid argument supplied for foreach() ["exception" => ErrorException { …}]
127.0.0.1 -  17/Feb/2022:19:17:40 +0300 "POST /index.php" 500
![2022-02-17_19-21-20]`
(https://user-images.githubusercontent.com/24496958/154524464-6722a0fc-c8a3-4153-af9b-df83594d2579.png)

**Comment by alexmorbo** [comment]
Привет!

Проблема все еще имеет место?

**Comment by eugene-ki** [comment]
> Привет!
> 
> Проблема все еще имеет место?
Добрый день.
Да, проблема актуальна.

**Comment by alexmorbo** [comment]
@eugene-ki а сейчас?

**Comment by eugene-ki** [comment]
Уже какое-то время работает. Спасибо!

пн, 26 сент. 2022 г., 11:34 Alex Morbo ***@***.***>:
