### ISSUE TITLE
Кнопки "ответить" и "сбросить".

### ISSUE THREAD

**Issue by lunguch** [alexmorbo/domru#18]
Уважаемый автор, подскажите, пожалуйста. У приложения дом.ru есть три кнопки при вызове. Открыть дверь, ответить и сбросить. Как можно использовать "сбросить вызов" или "поднять трубку"?

**Comment by alexmorbo** [comment]
Привет!

Никак, они работают по sip протоколу, это не имплементировать, к сожалению.
