### ISSUE TITLE
Добавление объектов

### ISSUE THREAD

**Issue by Sheredeka** [alexmorbo/domru#21]
Спасибо вам за ваш труд!!!!
Сделайте кнопку "Donate" - будем всеми поддерживать развитие интеграции

Можно ли как-то добавить объекты от интеграции типа camera для видео и например switch или button для кнопки открывания двери?
После установки вижу только это, а в объектах только сенсоры самой интеграции:
![изображение](https://user-images.githubusercontent.com/59475072/164468325-cb034dc9-329a-4b3f-a133-31174eb9ea59.png)

**Comment by ad** [comment]
@Sheredeka при нажатии на "Показать интеграцию в Home Assistant" не то что вам требуется?

**Comment by alexmorbo** [comment]
https://github.com/alexmorbo/domru/issues/24
