### ISSUE TITLE
На последних версиях HA камеры не добавляются

### ISSUE THREAD

**Issue by OXOTH1K** [alexmorbo/domru#27]
Начиная с версии примерно 2022.7.0 при попытке добавить камеру в HA через гуй - падает HA core с моментальным перезапуском. Куда посмотреть и что сказать я даже не знаю.

**Comment by alexmorbo** [comment]
Дублирует #26 

Фикс будет в начале следующей недели

**Comment by OXOTH1K** [comment]
Проблема актуальна. Фикс ситуацию не исправил
