### ISSUE TITLE
Аддон после обновления до 0.1.6 не запускается

### ISSUE THREAD

**Issue by dronix27** [alexmorbo/domru#31]
Home Assistant 2022.9.5
Supervisor 2022.09.1
Версия 0.1.6
[FATAL tini (7)] exec /opt/docker-entrypoint.sh failed: Exec format error

**Comment by dancer810** [comment]
Подтверждаю, после обновления не запускается, ошибка та же
[FATAL tini (7)] exec /opt/docker-entrypoint.sh failed: Exec format error

**Comment by isprite** [comment]
Тоже подтверждаю. Ошибка такая же.

**Comment by alexmorbo** [comment]
На каком устройстве установлено?

**Comment by isprite** [comment]
Windows 11, VirtualBox.

Home Assistant 2022.9.5
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2 - latest

**Comment by bonoirk** [comment]
Тоже подтверждаю ошибку. Работает в виртуальной машине на Synology NAS.
Home Assistant 2022.9.5
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2 - latest

**Comment by dronix27** [comment]
> На каком устройстве установлено?

Мини-ПК процессор x64 (Intel Celeron N3050)

**Comment by alexmorbo** [comment]
```
docker ps | grep domru
```

Что выводит, покажите, пожалуйста

**Comment by dronix27** [comment]
> 

Ничего

**Comment by dronix27** [comment]
> ```
> docker ps | grep domru
> ```
> 
> Что выводит, покажите, пожалуйста

Ничего

**Comment by alexmorbo** [comment]
Логично, а так?

```
docker ps -a | grep domru
```

**Comment by dancer810** [comment]
> Логично, а так?
> 
> ```
> docker ps -a | grep domru
> ```

62202c41a633   alexmorbo/domru-amd64:0.1.6                                "/opt/docker-entrypo…"   2 hours ago     Exited (1) 2 hours ago                                                         addon_a3e99f9a_domru

**Comment by alexmorbo** [comment]
> > Логично, а так?
> > ```
> > docker ps -a | grep domru
> > ```
> 
> 62202c41a633 alexmorbo/domru-amd64:0.1.6 "/opt/docker-entrypo…" 2 hours ago Exited (1) 2 hours ago addon_a3e99f9a_domru

а запусти `arch` ?

**Comment by dancer810** [comment]
> 

x86_64

**Comment by dronix27** [comment]
> > > Логично, а так?
> > > ```
> > > docker ps -a | grep domru
> > > ```
> > 
> > 
> > 62202c41a633 alexmorbo/domru-amd64:0.1.6 "/opt/docker-entrypo…" 2 hours ago Exited (1) 2 hours ago addon_a3e99f9a_domru
> 
> а запусти `arch` ?

x86_64 конечно

**Comment by dancer810** [comment]
> > > > Логично, а так?
> > > > ```
> > > > docker ps -a | grep domru
> > > > ```
> > > 
> > > 
> > > 62202c41a633 alexmorbo/domru-amd64:0.1.6 "/opt/docker-entrypo…" 2 hours ago Exited (1) 2 hours ago addon_a3e99f9a_domru
> > 
> > 
> > а запусти `arch` ?
> 
> X86_64 конечно

Не совсем понял что сделать?) команду arch кинул в консоль, вывод скинул.
Надо что то другое?

**Comment by dronix27** [comment]
> Логично, а так?
> 
> ```
> docker ps -a | grep domru
> ```

9502eb5ba2b9   alexmorbo/domru-amd64:0.1.6                                "/opt/docker-entrypo…"   About an hour ago   Exited (1) About an hour ago                                                                                                                                  addon_a3e99f9a_domru

**Comment by alexmorbo** [comment]
Gotcha, сейчас будет фикс

**Comment by alexmorbo** [comment]
```
docker pull alexmorbo/domru-amd64:0.1.6
```

Лечит ситуацию
