### ISSUE TITLE
Инструкция для HA без Supervisor

### ISSUE THREAD

**Issue by Dambo-nn** [alexmorbo/domru#32]
Добрый день.
Не могли бы вы написать краткую инструкцию по развертыванию контейнера для тех у кого нет Supervisor? И как пробросить кнопку открытия двери в HA?

**Comment by alexmorbo** [comment]
Без супервизора можно просто запустить докер контейнер, как-то так:
```
docker run -d -p 20080:80 --name addon_domru -v /path/to/home/assistant/share/domru/accounts:/share/domru/accounts alexmorbo/domru-amd64
```

amd64 - для amd64 архитектуры, остальные можно посмотреть [тут](https://hub.docker.com/u/alexmorbo)

Ну а в HA прокинуть уже по инструкции, которая показывается, внутри приложения.
