### ISSUE TITLE
Что это за ошибки?

### ISSUE THREAD

**Issue by Dambo-nn** [alexmorbo/domru#37]
Добрый день.

Подскажите, с чем связаны эти ошибки?

![Screenshot_1](https://user-images.githubusercontent.com/74897892/207593212-f1ae1b32-1b14-42db-8740-0b28df105309.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/74897892/207593394-cda2993a-45fa-4c1f-9de9-72d5abb528ab.jpg)

![Screenshot_3](https://user-images.githubusercontent.com/74897892/207593424-543bca38-86f7-440d-9d35-e3a79cebf8da.jpg)

Весь журнал ими забит, фиксируются постоянно. Как то можно от них избавится?

**Comment by alexmorbo** [comment]
ДомРу не стримит видопоток "вечно", в определенный момент он обрывается это и сигнализируется в этих ошибках

**Comment by Dambo-nn** [comment]
То есть это нормальное поведение? Или всё таки эти ошибки сообщают о проблемах на транспортной сети?
