### ISSUE TITLE
Отображается только один домофон

### ISSUE THREAD

**Issue by xMrVizzy** [alexmorbo/domru#6]
Скриншот из приложения:
![0F0F3D00-41D4-47D8-835A-61205CB089FA](https://user-images.githubusercontent.com/7906418/108579316-26291c00-7348-11eb-91c2-fbb853ed88e0.jpeg)

Скриншот из аддона:
![59EE6B71-E480-4733-8CB3-96E04815B5E9](https://user-images.githubusercontent.com/7906418/108579325-33460b00-7348-11eb-8b4d-80d4f587ae63.jpeg)

И ещё, если сравнить оба скриншота, то видно, что в аддоне камера взялась от калитки а название от подъезда.

**Comment by alexmorbo** [comment]
@xMrVizzy актуально еще?
