### ISSUE TITLE
Как добавить событие звонка в automations?

### ISSUE THREAD

**Issue by UksusoFF** [alexmorbo/domru#7]
Есть ли возможность отловить событие звонка?

**Comment by alexmorbo** [comment]
К сожалению нет.
Звонки идут через пуш уведомления, их отловить нет возможности.

Для этого можно использовать аппаратное решение, например:
- Wi-Fi - https://t.me/domofon_esp
- Zigbee - https://t.me/zigbeat/1172

**Comment by UksusoFF** [comment]
@alexmorbo аппаратное у меня уже есть) Хотелось бы от него отказаться в пользу интеграции.

**Comment by alexmorbo** [comment]
@UksusoFF к сожалению никак
