### ISSUE TITLE
Не могу авторизоваться

### ISSUE THREAD

**Issue by sshalyminov** [alexmorbo/domru#8]
Не могу авторизоваться в дополнении.
Ввожу номер телефона, дополнение правильно показывает номер договора и адрес, ввожу код из смс - получаю ошибку "Не найден профиль Клиента"
Домофон подключен через Цифрал, в личный кабинет и в приложение "Умный ДомРу" вхожу по номеру договора и паролю без проблем.

**Comment by sshalyminov** [comment]
В логе дополнения ошибок нет:

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  
11:45:09 DEBUG     [app] App\Service\HomeAssistant::async | Run
11:45:09 DEBUG     [app] Fetching finances for accounts
11:45:09 DEBUG     [app] Watchdog for finances complete
11:45:09 DEBUG     [app] Fetching profiles for accounts
11:45:09 DEBUG     [app] Watchdog for profiles complete
11:45:09 DEBUG     [app] Fetching cameras for accounts
11:45:09 DEBUG     [app] Watchdog for cameras complete
11:45:09 DEBUG     [app] Fetching subscriberPlaces for accounts
11:45:09 DEBUG     [app] Watchdog for subscriberPlaces complete
11:45:09 DEBUG     [app] [HA] Network info fetching complete
11:45:22 DEBUG     [app] HTTP request run ["parameters" => ["_controller" => "App\Command\RunCommand","_method" => "fetchFullInfo","_route" => "fetchFullInfo"],"args" => []]
127.0.0.1 -  04/Apr/2021:14:45:22 +0300 "GET /index.php" 302
127.0.0.1 -  04/Apr/2021:14:45:22 +0300 "GET /index.php" 200
127.0.0.1 -  04/Apr/2021:14:45:33 +0300 "POST /index.php" 200
127.0.0.1 -  04/Apr/2021:14:45:40 +0300 "GET /index.php" 200
127.0.0.1 -  04/Apr/2021:14:45:50 +0300 "POST /index.php" 200
127.0.0.1 -  04/Apr/2021:14:45:59 +0300 "POST /index.php" 200
11:46:03 DEBUG     [app] HTTP request run ["parameters" => ["_controller" => "App\Command\RunCommand","_method" => "fetchFullInfo","_route" => "fetchFullInfo"],"args" => []]
127.0.0.1 -  04/Apr/2021:14:46:03 +0300 "GET /index.php" 302
127.0.0.1 -  04/Apr/2021:14:46:03 +0300 "GET /index.php" 200
127.0.0.1 -  04/Apr/2021:14:46:38 +0300 "POST /index.php" 200
127.0.0.1 -  04/Apr/2021:14:47:09 +0300 "GET /index.php" 200
127.0.0.1 -  04/Apr/2021:14:55:38 +0300 "POST /index.php" 200
127.0.0.1 -  04/Apr/2021:14:55:40 +0300 "GET /index.php" 200
127.0.0.1 -  04/Apr/2021:14:55:52 +0300 "POST /index.php" 200

**Comment by alexmorbo** [comment]
Напишите в телеграм https://t.me/alexmorbo, нужно разобраться

**Comment by alexmorbo** [comment]
Авторищация по номеру договора и паролю не имплементирована.
Возможна только авторизация через номер телефона + смс

**Comment by WhiTeDiggeR** [comment]
Столкнулся с такой же проблемой. СМС приходит, но после указания кода пишет "Не найден профиль Клиента". Можно как-то обойти эту проблему?

**Comment by sshalyminov** [comment]
> Авторищация по номеру договора и паролю не имплементирована. Возможна только авторизация через номер телефона + смс

@alexmorbo мне подсказали как решить проблему. В приложении можно пригласить управлять домофоном ещё одного участника по номеру телефона. Я пригласил самого себя - и после этого по этим данным успешно авторизовался в аддоне. Примите к сведению как обходной вариант решения проблемы.
