### ISSUE TITLE
Отображаются не все камеры.

### ISSUE THREAD

**Issue by panfmik** [alexmorbo/domru#9]
У меня в доме 2 домофона с камерой, а в аддоне отоброжается только 1 и та которая дополнительная дверь.
Так же еще дополнительных 6 камер, а отоброжается только 5.

**Comment by alexmorbo** [comment]
Попробуйте обновиться на 0.1.5, скорее всего починилось
https://github.com/alexmorbo/domru/releases/tag/0.1.5

**Comment by panfmik** [comment]
проблема устранена
